[package]
edition = "2024"
name = "lineartgen"
version = "0.1.0"

[dependencies]
burn = { default-features = false, features = [
  "autodiff",
  "dataset",
  "fusion",
  "std",
  "train",
  "tui",
  "vision",
  "wgpu",
], version = "0.21.0" }
clap = { features = ["derive"], version = "4.5.51" }
image = { default-features = false, features = [
  "jpeg",
  "png",
], version = "0.25.10" }
