[package]
edition = "2024"
name = "lineartgen"
version = "0.1.0"

[dependencies]
burn = { default-features = false, features = [
  "autodiff",
  "dataset",
  "fusion",
  "std",
  "train",
  "tui",
  "vision",
  "vulkan",
  "flex",
], version = "0.21.0" }
clap = { features = ["derive"], version = "4.6.4" }
image = { default-features = false, features = [
  "jpeg",
  "png",
], version = "0.25.10" }
log = "0.4.33"
serde = { version = "1.0.229" ,features=["derive"]}
serde_json = "1.0.151"
png = "0.18.1"
rand = "0.10.2"
