[package]
edition = "2024"
name = "lineartgen-native"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]
name = "lineartgen_native"

[features]
default = ["flex"]
cube-cpu = ["lineartgen/inference-cpu"]
flex = ["lineartgen/inference-flex"]
vulkan-benchmark = ["lineartgen/inference-vulkan"]

[dependencies]
burn = { default-features = false, features = ["std"], version = "0.21.0" }
lineartgen = { default-features = false, path = "../.." }
pyo3 = { features = ["abi3-py310", "extension-module"], version = "0.29.0" }
rayon = "1.12.0"
